/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#35343e",
        "on-secondary-container": "#ffa17c",
        "on-primary-fixed-variant": "#3622ca",
        "on-surface": "#e4e1ee",
        "on-primary": "#2000a4",
        "surface-container-high": "#2a2933",
        "on-tertiary-container": "#003209",
        "error": "#ffb4ab",
        "surface-tint": "#c4c0ff",
        "primary-fixed-dim": "#c4c0ff",
        "on-error-container": "#ffdad6",
        "surface-bright": "#393842",
        "surface-container-highest": "#35343e",
        "on-secondary-fixed": "#370e00",
        "tertiary-fixed": "#b5f2af",
        "surface-dim": "#13121b",
        "on-secondary": "#5a1b00",
        "on-error": "#690005",
        "secondary-container": "#822d03",
        "surface-container-low": "#1b1b24",
        "inverse-surface": "#e4e1ee",
        "background": "#13121b",
        "error-container": "#93000a",
        "on-primary-fixed": "#100069",
        "surface-container": "#1f1f28",
        "on-tertiary-fixed": "#002204",
        "outline-variant": "#464555",
        "surface": "#13121b",
        "primary-container": "#8781ff",
        "on-surface-variant": "#c7c4d8",
        "on-tertiary": "#00390b",
        "on-secondary-fixed-variant": "#7f2b01",
        "inverse-on-surface": "#302f39",
        "secondary-fixed": "#ffdbce",
        "on-primary-container": "#1b0091",
        "secondary": "#ffb599",
        "outline": "#918fa1",
        "on-tertiary-fixed-variant": "#1b511f",
        "tertiary-fixed-dim": "#9ad594",
        "primary": "#c4c0ff",
        "tertiary": "#9ad594",
        "inverse-primary": "#4f44e2",
        "secondary-fixed-dim": "#ffb599",
        "on-background": "#e4e1ee",
        "tertiary-container": "#669e63",
        "primary-fixed": "#e3dfff",
        "surface-container-lowest": "#0e0d16"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter-grid": "24px",
        "base": "8px",
        "container-padding": "32px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "40px"
      },
      "fontFamily": {
        "display-md": ["Space Grotesk"],
        "mono-data": ["Space Grotesk"],
        "body-md": ["Sora"],
        "headline-lg-mobile": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "body-sm": ["Sora"],
        "label-caps": ["Sora"],
        "headline-lg": ["Space Grotesk"],
        "body-lg": ["Sora"]
      },
      "fontSize": {
        "display-md": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "mono-data": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "headline-lg": ["30px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
